# Generated by Django 5.1.7 on 2025-04-04 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('bandera', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_analisis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre_partido', models.CharField(max_length=255)),
                ('porcentaje_local', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_visitante', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_general', models.DecimalField(decimal_places=2, max_digits=5)),
                ('racha_local', models.CharField(max_length=100)),
                ('racha_visitante', models.CharField(max_length=100)),
                ('racha_hist_local', models.CharField(max_length=100)),
                ('racha_hist_visitante', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('APOSTADO', 'Apostado'), ('LIVE', 'Live'), ('NO', 'No')], max_length=10)),
                ('cumplido', models.CharField(blank=True, choices=[('VERDE', 'Cumplido'), ('ROJO', 'No cumplido'), (None, 'Sin resultado')], max_length=6, null=True)),
                ('notas', models.TextField(blank=True)),
                ('liga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.liga')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='general.metodoanalisis')),
            ],
        ),
    ]
