# Generated by Django 5.1.7 on 2025-04-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liga',
            name='bandera',
        ),
        migrations.AddField(
            model_name='liga',
            name='codigo_pais',
            field=models.CharField(default='ES', max_length=2),
        ),
    ]
