# Generated by Django 5.1.7 on 2025-04-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_liga_bandera_liga_codigo_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='codigo_pais',
            field=models.CharField(default='ES', max_length=6),
        ),
    ]
