# Generated by Django 5.1.7 on 2025-04-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_liga_codigo_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='equipo_destacado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
