# Generated by Django 5.1.7 on 2025-04-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_partido_equipo_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='racha_hist_local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='racha_hist_visitante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='racha_local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='racha_visitante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
