# Generated by Django 5.1.7 on 2025-04-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_suscripcion_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
