# Generated by Django 5.1.7 on 2025-04-13 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_suscripcion_cancelada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('equipo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('LOCAL', 'Local'), ('VISITANTE', 'Visitante')], max_length=10)),
                ('analizar', models.TextField()),
                ('stake', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_analisis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
