# Generated by Django 5.1.7 on 2025-04-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_notaanalisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaanalisis',
            name='cumplido',
            field=models.CharField(blank=True, choices=[('VERDE', 'Cumplido'), ('ROJO', 'No cumplido'), (None, 'Sin resultado')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notaanalisis',
            name='estado',
            field=models.CharField(choices=[('APOSTADO', 'Apostado'), ('LIVE', 'Live'), ('NO', 'No')], default='NO', max_length=50),
        ),
    ]
