# Generated by Django 5.1.7 on 2025-04-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_notaanalisis_cumplido_alter_notaanalisis_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaanalisis',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]
